// podcastrangular/src/app/components/player/player.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { Store, select } from '@ngrx/store'
import { togglePlay, playNext, clearPlayingState, playingState, playPrevious, toggleLoop, toggleShuffle, progress } from '../../contexts/PlayerContext/PlayerContext'
import { convertDurationToTimeString } from '../../utils/convertDuration'

type Episode = {
  title: string;
  members: string;
  thumbnail: string;
  duration: number;
  url: string;
}

@Component({
  selector: 'app-player',
  templateUrl: './player.component.html',
  styleUrls: ['./player.component.scss']
})
export class PlayerComponent implements OnInit {
  public episode: Episode
  public hasNext: boolean
  public hasPrevious: boolean
  public isPlaying: boolean
  public isShuffeling: boolean
  public isLooping: boolean
  public episodeList: Episode[]
  public currentEpisodeIndex: number

  public player$: Observable<any>
  public progress$: Observable<any>

  constructor(private store: Store<any>) { }

  ngOnInit(): void {
    this.loadStatePlayer()
    this.loadStateProgress()

    this.player$.subscribe((state) => {
      this.episode = state.episodeList[state.currentEpisodeIndex]
      this.hasNext = state.hasNext
      this.isPlaying = state.isPlaying
      this.isLooping = state.isLooping
      this.isShuffeling = state.isShuffeling
      this.episodeList = state.episodeList
      this.currentEpisodeIndex = state.currentEpisodeIndex
      this.hasNextVerify()
      this.hasPreviousVerify()
    })
  }

  loadStatePlayer (): void {
    this.player$ = this.store.pipe(select('playerReducer'))
  }

  loadStateProgress (): void {
    this.progress$ = this.store.pipe(select('progressReducer'))
  }

  togglePlay () {
    this.store.dispatch(togglePlay())

    const audio = <HTMLAudioElement>document.getElementById('player')
    if (this.isPlaying) {
      audio.play()
    } else {
      audio.pause()
    }
  }

  hasNextVerify () {
    this.hasNext = this.isShuffeling || (this.currentEpisodeIndex + 1) < this.episodeList.length
  }

  hasPreviousVerify () {
    this.hasPrevious = this.currentEpisodeIndex > 0
  }

  convertDuration (duration: number) {
    return convertDurationToTimeString(duration)
  }

  handleEpisodeEnded () {
    if (this.hasNext) {
      this.store.dispatch(playNext())
    } else {
      this.store.dispatch(clearPlayingState())
    }
  }

  setProgressListener() {
    const audio = <HTMLAudioElement>document.getElementById('player')
    audio.currentTime = 0

    audio.addEventListener('timeupdate', () => {
      this.store.dispatch(progress({ progress: Math.floor(audio.currentTime)}))
    })
  }

  playNext () {
    this.store.dispatch(playNext())
  }

  playPrevious () {
    this.store.dispatch(playPrevious())
  }

  playingState (state: boolean) {
    this.store.dispatch(playingState({ state }))
  }

  toggleLoop () {
    this.store.dispatch(toggleLoop())
  }

  toggleShuffle () {
    this.store.dispatch(toggleShuffle())
  }
}

<div class=playerContainer>
  <header>
    <img src="../../../assets/img/playing.svg" alt="Tocando agora"/>
    <strong>Tocando agora</strong>
  </header>

  <div class="currentEpisode" *ngIf="episode; else emptyPlayer">
    <img width="197" height="197" src="{{episode.thumbnail}}" style="object-fit: cover;"/>
    <strong>{{episode.title}}</strong>
    <span>{{episode.members}}</span>
  </div>

  <div class="slider">
    <div class="emptySlider"></div>
  </div>

  <footer class="empty">
    <div class="progress">
      <span>{{convertDuration((progress$ | async).progress)}}</span>
      <div class="slider">
      <div class="emptySlider"></div>
      </div>
      <span>{{convertDuration(episode?.duration || 0)}}</span>
    </div>

    <audio
      id="player"
      src="{{episode?.url}}"
      autoplay="true"
      (play)="playingState(true)"
      (pause)="playingState(false)"
      (ended)="handleEpisodeEnded()"
      (loadedmetadata)="setProgressListener()"
    ></audio>

    <div class="buttons">
      <button type="button" [ngClass]="isShuffeling? 'isActive' : ''" [disabled]="!episode" (click)="toggleShuffle()">
        <img src="../../../assets/img/shuffle.svg" alt="Embaralhar"/>
      </button>

      <button type="button" [disabled]="!episode|| !hasPrevious" (click)="playPrevious()">
        <img src="../../../assets/img/play-previous.svg" alt="Tocar anterior"/>
      </button>
      <button type="button" class="playButton" [disabled]="!episode" (click)="togglePlay()">
        <img *ngIf="(player$ | async).isPlaying" src="../../../assets/img/pause.svg" alt="Pausar"/> 
        <img *ngIf="!(player$ | async).isPlaying" src="../../../assets/img/play.svg" alt="Tocar"/> 
      </button>

      <button type="button" [disabled]="!episode || !hasNext" (click)="playNext()">
        <img src="../../../assets/img/play-next.svg" alt="Tocar próxima"/>
      </button>

      <button type="button" [ngClass]="isLooping? 'isActive' : ''" [disabled]="!episode" (click)="toggleLoop()">
        <img src="../../../assets/img/repeat.svg" alt="Repetir"/>
      </button>
    </div>
  </footer>
</div>

<ng-template #emptyPlayer>
  <div class="emptyPlayer">
    <strong>Selecione um podcast para ouvir</strong>
  </div>
</ng-template>

// podcastrnext/src/components/Player/index.tsx
import Image from "next/image"
import { useRef, useEffect, useState } from "react"
import Slider from 'rc-slider'
import 'rc-slider/assets/index.css'

import styles from "./styles.module.scss"
import { usePlayer } from "../../contexts/PlayerContext"
import { convertDurationToTimeString } from "../../utils/convertDuration"

export function Player () {
  const audioRef = useRef<HTMLAudioElement>(null)
  const [progress, setProgress] = useState(0)

  const {
    episodeList,
    currentEpisodeIndex,
    isPlaying,
    isLooping,
    isShuffeling,
    togglePlay,
    toggleLoop,
    toogleShuffle,
    setPlayingState,
    clearPlayingState,
    playNext,
    playPrevious,
    hasNext,
    hasPrevious
  } = usePlayer()
  
  useEffect(() => {
    if (!audioRef.current) {
      return;
    }
    
    if (isPlaying) {
      audioRef.current.play()
    } else {
      audioRef.current.pause()
    }
  }, [isPlaying])

  function setProgressListener() {
    audioRef.current.currentTime = 0

    audioRef.current.addEventListener('timeupdate', () => {
      setProgress(Math.floor(audioRef.current.currentTime))
    })
  }

  function handleSeek (amount: number) {
    audioRef.current.currentTime = amount
    setProgress(amount)
  }

  function handleEpisodeEnded () {
    if (hasNext) {
      playNext()
    } else {
      clearPlayingState()
    }
  }
  
  const episode = episodeList[currentEpisodeIndex]
  
  return (
    <div className={styles.playerContainer}>
      <header>
        <img src="/playing.svg" alt="Tocando agora"/>
        <strong>Tocando agora</strong>
      </header>

      { episode ? (
        <div className={styles.currentEpisode}>
          <Image width={592} height={592} src={episode.thumbnail} objectFit="cover" />
          <strong>{episode.title}</strong>
          <span>{episode.members}</span>
        </div>
      ) : (
        <div className={styles.emptyPlayer}>
          <strong>Selecione um podcast para ouvir</strong>
        </div>
      ) }

      <footer className={!episode ? styles.empty: ''}>
        <div className={styles.progress}>
          <span>{convertDurationToTimeString(progress)}</span>
          <div className={styles.slider}>
            { episode ? (
              <Slider 
                max={episode.duration}
                value={progress}
                onChange={handleSeek}
                trackStyle={{ backgroundColor: '#04d361'}}
                railStyle={{ backgroundColor: '#9f75ff'}}
                handleStyle={{ borderColor: '#04d361', borderWidth: 4 }}
              />
            ) : (
              <div className={styles.emptySlider}></div>
            ) }
          </div>
          <span>{convertDurationToTimeString(episode?.duration ?? 0)}</span>
        </div>

        { episode && (
          <audio
            src={episode.url}
            ref={audioRef}
            autoPlay
            loop={isLooping}
            onEnded={handleEpisodeEnded}
            onPlay={() => setPlayingState(true)}
            onPause={() => setPlayingState(false)}
            onLoadedMetadata={setProgressListener}
            ></audio>
        ) }

        <div className={styles.buttons}>
          <button
            type="button"
            disabled={!episode || episodeList.length === 1}
            onClick={toogleShuffle}
            className={isShuffeling ? styles.isActive : ''}
          >
            <img src="/shuffle.svg" alt="Embaralhar"/>
          </button>

          <button type="button" disabled={!episode || !hasPrevious} onClick={playPrevious}>
            <img src="/play-previous.svg" alt="Tocar anterior"/>
          </button>

          <button type="button" className={styles.playButton} disabled={!episode} onClick={togglePlay}>
            { isPlaying ? 
              <img src="/pause.svg" alt="Pausar"/> 
            : <img src="/play.svg" alt="Tocar"/> 
            }
          </button>

          <button type="button" disabled={!episode || !hasNext} onClick={playNext}>
            <img src="/play-next.svg" alt="Tocar próxima"/>
          </button>

          <button
            type="button"
            disabled={!episode}
            onClick={toggleLoop}
            className={isLooping ? styles.isActive : ''}
          >
            <img src="/repeat.svg" alt="Repetir"/>
          </button>
        </div>
      </footer>
    </div>
  )
}
