// podcastrangular/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import format from 'date-fns/format'
import ptBR from 'date-fns/locale/pt-BR'

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  public currentDate: string

  constructor() { }

  ngOnInit(): void {
    this.currentDate = format(new Date, 'EEEEEE, d MMMM', {
      locale: ptBR,
    })
  }

}

<header class="headerContainer">
    <img src="../../../assets/img/logo.svg" alt="Podcastr" />

    <p>O melhor para você ouvir, sempre</p>

    <span>{{currentDate}}</span>
</header>

// podcastrnext/src/components/Header/index.tsx
import styles from "./styles.module.scss"
import format from 'date-fns/format'
import ptBR from 'date-fns/locale/pt-BR'

export function Header () {
  const currentDate = format(new Date, 'EEEEEE, d MMMM', {
    locale: ptBR,
  })

  return (
    <header className={styles.headerContainer}>
      <img src="/logo.svg" alt="Podcastr" />

      <p>O melhor para você ouvir, sempre</p>

      <span>{currentDate}</span>
    </header>
  )
}
